### ISSUE TITLE
Docker image is not running

### ISSUE THREAD

**Issue by raefezzeldin** [tokern/data-lineage#29]
The docker image doesn’t run successfully. And I can’t run init or runserver command

**Comment by vrajat** [comment]
Hi @raefezzeldin Thanks for trying out the data lineage app. I am in the process of over-hauling the app based on feedback from users. Some of the changes I am making are:
* persisting the catalog and lineage in a database
* Adding jobs to the data model and lineage graph
* Column Level Lineage
* Revamping the architecture to make it easier to add support for more databases.

I'll keep you informed when these changes are done. In the meantime, can you take this [survey](https://forms.gle/WadW4EDRLF3FXttt6) to help me understand your use case?

**Comment by vrajat** [comment]
@raefezzeldin I've updated the docker image and provided a docker-compose that runs data-lineage with demo data. Instructions are here: https://tokern.io/docs/data-lineage/installation

Please take a look.

**Comment by raefezzeldin** [comment]
It looks great. I will try to deploy my environment on it

**Comment by vrajat** [comment]
Resolving this issue. Please reopen if you cannot run the docker images of the latest versions.
