### ISSUE TITLE
Not an issue with data-lineage but issue with required package: pglast

### ISSUE THREAD

**Issue by siva-mudiyanur** [tokern/data-lineage#41]
Opening this issue to let everyone know till it gets fixed...the installation for pglast fails requiring a xxhash.h file. Here's the link to issue and how to resolve it: [https://github.com/lelit/pglast/issues/82](https://github.com/lelit/pglast/issues/82)

Please feel free to close if you think its inappropriate

**Comment by vrajat** [comment]
Thank you. I'll close it once the fix in pglast is resolved and a new version is available. 

I am moving this to a new architecture where data-lineage is run as a server and the SDK has much smaller list of dependencies.

**Comment by siva-mudiyanur** [comment]
Great..I'm excited for it, just to confirm..data-lineage is already available to run as a server right? I'm yet to explore..I only tried the sample docker image so far.

**Comment by vrajat** [comment]
Fixed by updating to pglast v3.3
