### ISSUE TITLE
CTE visiting

### ISSUE THREAD

**Issue by dhuettenmoser** [tokern/data-lineage#42]
Currently it doesn't appear that the dml_visitor will walk through the common table expressions to build the lineage. Am I interpreting this wrong? Within vistor.py line 45 and 61 both visit the "with clause". There doesn't seem to be any functionality for handling the commontableexpr or ctes within the parsed statments. This causes any statements with ctes to throw an error when calling parse_queries, as no table is found when attempting to bind a CTE in a FROM clause.

**Comment by vrajat** [comment]
I am assuming you are parsing Redshift queries. lelit/pglast and pganalyze/libpg_query parse postgres SQL dialect. I have a fork of these projects where I am modifying the syntax for redshift. Can you provide an example so that I can test a fix?

**Comment by vrajat** [comment]
Pretty printed python dict of the plan:

    [{'RawStmt':
      {'stmt': {
        'InsertStmt': {
          'relation': {
            'RangeVar': {
              'relname': 'page_lookup_redirect', 'inh': True, 'relpersistence': 'p', 'location': 64
            }
          },
          'cols': [
            {'ResTarget': {'name': 'redirect_title', 'location': 86}},
            {'ResTarget': {'name': 'true_title', 'location': 102}},
            {'ResTarget': {'name': 'page_id', 'location': 114}},
            {'ResTarget': {'name': 'page_version', 'location': 123}}
          ],
          'selectStmt': {
            'SelectStmt': {
              'targetList': [
                {'ResTarget': {'val': {'ColumnRef': {'fields': [{'String': {'str': 'redirect_title'}}], 'location': 144}}, 'location': 144}},
                {'ResTarget': {'val': {'ColumnRef': {'fields': [{'String': {'str': 'true_title'}}], 'location': 160}}, 'location': 160}},
                {'ResTarget': {'val': {'ColumnRef': {'fields': [{'String': {'str': 'page_id'}}], 'location': 172}}, 'location': 172}},
                {'ResTarget': {'val': {'ColumnRef': {'fields': [{'String': {'str': 'page_version'}}], 'location': 181}}, 'location': 181}}
              ],  
              'fromClause': [{'RangeVar': {'relname': 'pln', 'inh': True, 'relpersistence': 'p', 'location': 199}}], 'op': 0
            }
          },
          'withClause': {
            'WithClause': {
              'ctes': [{
                'CommonTableExpr': {
                  'ctename': 'pln', 
                  'ctequery': {
                    'SelectStmt': {
                      'targetList': [
                        {'ResTarget': {'val': {'ColumnRef': {'fields': [{'A_Star': {}}], 'location': 20}}, 'location': 20}}
                      ], 
                      'fromClause': [
                        {'RangeVar': {
                          'relname': 'page_lookup_nonredirect', 'inh': True, 'relpersistence': 'p', 'location': 27}}
                      ],
                      'op': 0
                    }
                  },
                  'location': 5
                }
              }]
            }
          },
          'override': 0
        }
      },
      'stmt_len': 202
     }
    }]

**Comment by dhuettenmoser** [comment]
This looks like I'd expect and like I found when exploring what is returned by parse_queries. The issue I've run into occurs when passing the catalog and this into visit_dml_query 
https://github.com/tokern/data-lineage/blob/master/data_lineage/parser/__init__.py#L30
I havent tested with this specific query, but I would expect a " 'pnl' table not found" error to occur in testing it. (From:
https://github.com/tokern/dbcat/blob/main/dbcat/catalog/catalog.py#L351 , called from: 
https://github.com/tokern/data-lineage/blob/master/data_lineage/parser/dml_visitor.py#L75

**Comment by vrajat** [comment]
I created a PR with experimental support. This is by no way complete but checking if it is directionally correct. Lot more cases and testing needs to be done.

**Comment by vrajat** [comment]
Also `select * ` queries are not supported. I file a new issue for that.

**Comment by vrajat** [comment]
I have added basic support for WITH clause. BASIC because I tested 3 variants of a WITH clause. There is a good chance that more complex queries may fail. Can you please test it out and file issues for queries that do not work?

**Comment by dhuettenmoser** [comment]
thanks! I'll start testing this out and let you know about any issues I run into.
