### ISSUE TITLE
problem with docker-compose

### ISSUE THREAD

**Issue by kirill3000** [tokern/data-lineage#49]
Hello! 
i use this docs
https://tokern.io/docs/data-lineage/installation

1 curl https://raw.githubusercontent.com/tokern/data-lineage/master/install-manifests/docker-compose-demodb/docker-compose.yml -o docker-compose.yml
2 docker-compose up -d
3 get error 
ERROR: In file './docker-compose.yml', the services name 404 must be a quoted string, i.e. '404'.

**Comment by vrajat** [comment]
Oops - I reorganized the folders and havent updated the website. Thanks for pointing it out. Can you try this command instead?

    curl https://raw.githubusercontent.com/tokern/data-lineage/master/install-manifests/docker-compose/docker-compose-demo-catalog.yml -o docker-compose.yml


Also can you please answer this [survey](https://forms.gle/p2oEQBJnpEguhrp3A) It will help me understand your use case.

**Comment by kirill3000** [comment]
yes, it's work!
Shell i ask you to add some documentation how ti change nodes or datasets ?
![image](https://user-images.githubusercontent.com/22203338/122925393-730d1580-d36f-11eb-88a5-639cfbee7a1e.png)

**Comment by vrajat** [comment]
Please check out the [example API code](https://github.com/tokern/data-lineage/blob/master/api_example.ipynb) to understand the current capabilities. The next major update is to make it easier to add nodes and edges. Can you fill the survey? That will help me prioritize the work.

**Comment by kirill3000** [comment]
I filled  the survey, thank you!
