### ISSUE TITLE
Testing api_example.ipynb

### ISSUE THREAD

**Issue by kirill3000** [tokern/data-lineage#51]
I tried run exapmple

https://github.com/tokern/data-lineage/blob/master/api_example.ipynb

i got error
![image](https://user-images.githubusercontent.com/22203338/123332928-ce92fb00-d549-11eb-8e76-5a02b1ea3392.png)

Could you tell me how i can fix it
Thank you

**Comment by vrajat** [comment]
Can you please change the cell contents to:

    import logging
    logging.basicConfig(level=logging.DEBUG)
    catalog.scan_source(source)

The above will provide debug logs to help find the root cause.

**Comment by kirill3000** [comment]
thank you!
no errors
![image](https://user-images.githubusercontent.com/22203338/123616707-39288d00-d80f-11eb-89ef-d977a51eb9e1.png)

**Comment by vrajat** [comment]
Can you run `docker container ls | grep tokern` at the command line and paste the output?

**Comment by kirill3000** [comment]
b8430ff89f31   tokern/data-lineage-viz:latest          "/docker-entrypoint.…"   7 days ago      Up 7 days                0.0.0.0:8000->80/tcp, :::8000->80/tcp                                                            tokern-data-lineage-visualizer
a6466297839d   tokern/data-lineage:latest              "data_lineage"           7 days ago      Up 7 days                                                                                                                 tokern-data-lineage
cd5d96163027   tokern/demo-catalog:latest              "docker-entrypoint.s…"   7 days ago      Up 7 days                                                                                                                 tokern-demo-catalog

**Comment by vrajat** [comment]
Sorry for the confusion. The documentation and examples havent kept up to date with API changes I've been implementing. I am running a fix now. The examples need a separate docker-compose file that runs all the components required.

Please clean up your setup:

    docker-compose -f <path to docker-compose-demo-catalog> down
    docker volume prune # Note that this may delete other volumes not related to tokern container. Please run with caution

In the git directory

    git pull
    docker image pull

Then follow the instructions in `api_example.ipynb`
