### ISSUE TITLE
Conflicting package dependencies

### ISSUE THREAD

**Issue by siva-mudiyanur** [tokern/data-lineage#56]
amundsen-databuilder which is one of the package dependencies for dbcat [requires](https://github.com/amundsen-io/amundsen/blob/f421208178f9a6ab4ac235037314e02933da51f9/requirements-common.txt#L13) flask 1.0.2 whereas data-lineage  [requires](https://github.com/tokern/data-lineage/blob/fb97910e869119a891d5f0cc4b73e14dc220f66a/setup.py#L70) flask 1.1

Please feel free to close if its not a valid issue.

**Comment by vrajat** [comment]
I moved the build system to poetry. So poetry.lock is the source of truth. This is right now using [flask 1.1.4](https://github.com/tokern/data-lineage/blob/master/poetry.lock#L484). Looks like they reverted to [hard pinning](https://github.com/amundsen-io/amundsen/pull/1267) a few days ago. The latest changes will get picked up when I update the versions in dbcat.

Thanks for pointing this out.

I'll also delete setup.py as it is not used anymore and is replaced with pyproject.toml

**Comment by vrajat** [comment]
[Amundsen can work](https://github.com/amundsen-io/amundsen/blob/main/common/setup.py#L26) with 1.x version of flask.
