### ISSUE TITLE
Debian Buster can't find version

### ISSUE THREAD

**Issue by jesusjackson** [tokern/data-lineage#70]
Hi, I'm trying to install the 0.8 version on a docker that runs on Debian Buster and when it runs the pip command to install it prints the following warning/error:
```
#12 9.444 Collecting data-lineage==0.8.0 (from -r /project/requirements.txt (line 25))
#12 9.466   Could not find a version that satisfies the requirement data-lineage==0.8.0 (from -r /project/requirements.txt (line 25)) (from versions: 0.1.2, 0.2.0, 0.3.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0)
#12 9.541 No matching distribution found for data-lineage==0.8.0 (from -r /project/requirements.txt (line 25))
```
Is this normal behavior? Do I have to add something before trying to install?

**Comment by vrajat** [comment]
Hi
Looks like you are adding data-lineage as a dependency for one of your projects. I am surprised pip is not able to find 0.8.0. I can see that the version is listed in pypi: https://pypi.org/project/data-lineage/0.8.0/

Are you using a mirror of pyp.org? 

Also, can you use the latest patch version by changing the constraint to `^0.8`?

**Comment by jesusjackson** [comment]
Hi, thank you for the response, I was able to fix this by rebuiling the docker image. Seems that the older debian that we used previously was refusing to die. Now I'm facing something even weirder where I run the `pip3 install data-lineage`
```
        CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
        Could NOT find Arrow (missing: ARROW_INCLUDE_DIR ARROW_LIB_DIR
        ARROW_FULL_SO_VERSION ARROW_SO_VERSION)
```
Even tho I ran the whole process of installing arrow as described in their documentation.

**Comment by vrajat** [comment]
I am surprised too. data-lineage doesn't explicitly depend on arrow. I need to dig into dependencies to see which package is pulling it in. I haven't noticed arrow compilation when I install data-lineage also.

Can you use the pre-built containers ?

**Comment by jesusjackson** [comment]
Unfortunately no, I'll talk with the ops people in the company if there is anything they can do about this, because I have to use containers that they built. Thank you very much for all your help.

**Comment by vrajat** [comment]
The project uses poetry to build & package.

    poetry show --tree | grep arrow

Did not show any results. Still surprised that pip is installing arrow. Please keep me informed if you get a chance to figure it out.
