### ISSUE TITLE
Any way to increase timeout for scanning?

### ISSUE THREAD

**Issue by peteclark3** [tokern/data-lineage#73]
When I add my snowflake DB for scanning, using this bit of code (with the values replaced as per my snowflake database):
```
from data_lineage import Catalog

catalog = Catalog(docker_address)

# Register wikimedia datawarehouse with data-lineage app.

source = catalog.add_source(name="wikimedia", source_type="postgresql", **wikimedia_db)

# Scan the wikimedia data warehouse and register all schemata, tables and columns.

catalog.scan_source(source)
```

... I get 
```
tokern-data-lineage-visualizer | 2021/10/08 21:51:40 [error] 34#34: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.10.0.1, server: , request: "POST /api/v1/catalog/scanner HTTP/1.1", upstream: "http://10.10.0.3:4142/api/v1/catalog/scanner", host: "127.0.0.1:8000"
```

... I think it's because snowflake isn't returning fast enough... but I'm not sure.  Tried updating the warehouse size to large to make the scan faster, but getting the same thing.  Seems like it times out pretty fast... at least for my large database.  Any ideas?  

Python 3.8.0 in an isolated venv, 0.8.3 data-lineage.  Thanks for this package!

**Comment by vrajat** [comment]
Can you paste logs from the docker container? 

`docker container ls` will give you the ids of the tokern containers.

`docker container logs <id>` will paste the logs to the terminal.

**Comment by peteclark3** [comment]
Sorry I should have said - that is actually the log line from the docker container that appears when the python code throws the exception.

**Comment by peteclark3** [comment]
> Right. I think the worker timeout is the root cause. Let me dig in a bit into the code and see why it might be happening.

I really appreciate it!! 🙏
