### ISSUE TITLE
Snowflake source defaulting to prod even though I'm specifying a different db name

### ISSUE THREAD

**Issue by peteclark3** [tokern/data-lineage#75]
I'm adding a snowflake source as follows.. where `sf_db_name` is my database name e.g. `snowfoo` (verified in debugger)...

```
 source = catalog.add_source(name=f"sf1_{time.time_ns()}", source_type="snowflake", database=sf_db_name, username=sf_username, password=sf_password, account=sf_account, role=sf_role, warehouse=sf_warehouse)
```
... but when it goes to scan, it looks like the code thinks my database name is 'prod':

```
tokern-data-lineage | sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (02000): SQL compilation error:
tokern-data-lineage | Database 'PROD' does not exist or not authorized.
tokern-data-lineage | [SQL:
tokern-data-lineage |     SELECT
tokern-data-lineage |         lower(c.column_name) AS col_name,
tokern-data-lineage |         c.comment AS col_description,
tokern-data-lineage |         lower(c.data_type) AS col_type,
tokern-data-lineage |         lower(c.ordinal_position) AS col_sort_order,
tokern-data-lineage |         lower(c.table_catalog) AS database,
tokern-data-lineage |         lower(c.table_catalog) AS cluster,
tokern-data-lineage |         lower(c.table_schema) AS schema,
tokern-data-lineage |         lower(c.table_name) AS name,
tokern-data-lineage |         t.comment AS description,
tokern-data-lineage |         decode(lower(t.table_type), 'view', 'true', 'false') AS is_view
tokern-data-lineage |     FROM
tokern-data-lineage |         prod.INFORMATION_SCHEMA.COLUMNS AS c
tokern-data-lineage |     LEFT JOIN
tokern-data-lineage |         prod.INFORMATION_SCHEMA.TABLES t
tokern-data-lineage |             ON c.TABLE_NAME = t.TABLE_NAME
tokern-data-lineage |             AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
tokern-data-lineage |      ;
tokern-data-lineage |     ]
tokern-data-lineage | (Background on this error at: http://sqlalche.me/e/13/f405)
```

.. I'm trying to look through the tokern code repos to see where the disconnect might be happening, but not sure yet...

**Comment by vrajat** [comment]
`prod` is default in the [amundsen extractor](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/snowflake_metadata_extractor.py#L74). 

I do set the DATABASE_KEY [here](https://github.com/tokern/dbcat/blob/main/dbcat/catalog/db.py#L204). 

One bug is that I should be setting it `source.database` probably. However that still doesnt solve the problem of why the default is being used.

**Comment by peteclark3** [comment]
Happy to help in general in terms of testing with snowflake... if it helps you, as it will help me too!

**Comment by peteclark3** [comment]
Looks like it's scanning now but getting lots of 
```
tokern-catalog    | 2021-10-14 13:52:05.252 UTC [36] DETAIL:  Key (source_id, name)=(142, foo) already exists.
tokern-catalog    | 2021-10-14 13:52:05.252 UTC [36] STATEMENT:  INSERT INTO schemata (name, source_id) VALUES ('foo', 142) RETURNING schemata.id
tokern-catalog    | 2021-10-14 13:52:08.597 UTC [36] ERROR:  duplicate key value violates unique constraint "unique_schema_name"
tokern-catalog    | 2021-10-14 13:52:08.597 UTC [36] DETAIL:  Key (source_id, name)=(142, bar) already exists.
tokern-catalog    | 2021-10-14 13:52:08.597 UTC [36] STATEMENT:  INSERT INTO schemata (name, source_id) VALUES ('bar', 142) RETURNING schemata.id
tokern-catalog    | 2021-10-14 13:52:08.675 UTC [36] ERROR:  duplicate key value violates unique constraint "unique_schema_name"
```

Another issue though (can open a sep ticket if desired) is that while the above keeps running, I get a `504 Server Error: Gateway Time-out for url: http://127.0.0.1:8000/api/v1/catalog/scanner` - different error than the gunicorn one from previous... is this nginx timing out now instead of gunicorn?

**Comment by vrajat** [comment]
You can ignore the duplicate value. That is code being lazy in not running `check and insert` queries. You are right about nginx timing out. I'll create a new issue. I have an experimental branch with workers. I'll dust it up and merge it in. Also I am away for a week. I'll make some progress on all the issues by end of next week. Thank you for taking the effort to file these issues.
