### ISSUE TITLE
Support for large queries

### ISSUE THREAD

**Issue by peteclark3** [tokern/data-lineage#77]
calling 
```                    
analyze.analyze(**{"query":query}, source=dl_source, start_time=datetime.now(), end_time=datetime.now())
```
with a large query,  ​I get a "request too long" - seems that even though it is POSTing, it's still appending the query to the URL, thus the request fails.. e.g.

```
tokern-data-lineage-visualizer | 10.10.0.1 - - [14/Oct/2021:14:39:00 +0000] "POST /api/v1/analyze?query=ANY_REALLY_LONG_QUERY_HERE
```

**Comment by vrajat** [comment]
Ack. I'll take a look at how to solve this. However, I quick solution is to compress and send. I'll check if this will work. 

Aside: I typically cheat and use the library directly.
