### ISSUE TITLE
[Feature Request] Support Snowflake

### ISSUE THREAD

**Issue by manugarri** [tokern/data-lineage#9]
It would be neat

**Comment by vrajat** [comment]
This is a valid request. I don’t have access to a Snowflake database to test. Are you open to working with me to add support ? 

I need help with sample queries and testing.

**Comment by vrajat** [comment]
I am working on adding support to snowflake. Will you try it out? I am looking for users to trying it out and give me feedback.

**Comment by vrajat** [comment]
There is basic support for Snowflake now. Please check this blog post https://tokern.io/blog/data-lineage-on-snowflake/ and give me feedback if it works for you.
